### PR TITLE
fix: fixed the problem that `"` was not removed when the cli switched…

### LINKED ISSUE #1105: [BUG] failed to change database;
Describe the bug
I have a database named OceanicStaion. But I can't use it by cmd \c or use in cnosdb-cli.
version: cnosdb v2.2.0.
env:I deploied a 1m3d cluster in k8s.

To Reproduce
1、create database 'OceanicStation';
2、show databases;
3、\c OceanicStaion; or \c 'OceanicStaion'; or use 'OceanicStation';

Additional context
image
image
image

### PR DESCRIPTION
**Pull request by ZuoTiJia**
… databases

Closes #1105

### CODE REVIEW

File: client/src/exec.rs [hunk 1]
```diff
@@ -162,18 +162,19 @@ async fn exec_and_print(
...
+    let database = sql[3..].trim();
 
-    if sql.starts_with('"') && sql.ends_with('"') {
-        Some(sql[1..sql.len() - 1].to_string())
+    if database.starts_with('"') && database.ends_with('"') {
+        Some(database.trim_matches('"').to_string())
     } else {
-        Some(sql.to_string())
+        // normalize ident
+        Some(database.to_ascii_lowercase())
```
Comment (yukkit) [inline client/src/exec.rs:177]: Is it possible to not change the string，because it will be coupled with the server

Comment (ZuoTiJia) [reply client/src/exec.rs:177]: But here the cli needs to prompt the user for the name of the database

**Review by yukkit — APPROVED** [review]
