### PR TITLE
fix #480 : fix flush bug

### LINKED ISSUE #480: [Bug]Tsm flush request error
**Describe the bug**
only 1 tsm will be flush

**To Reproduce**
run kvcore big write test

**Expected behavior**
normal request

**Additional context**
none

### PR DESCRIPTION
**Pull request by Subsegment**
# Which issue does this PR close?

Closes #480 .

 # Rationale for this change

fix bug

# What changes are included in this PR?

flushing shoulb be changed after req is ok

# Are there any user-facing changes?

none

### CODE REVIEW

File: tskv/src/kvcore.rs [hunk 1]
```diff
@@ -590,15 +590,17 @@ mod test {
...
-        let points = fbb.finished_data().to_vec();
+        for i in 0..100 {
+            let database = "db".to_string();
+            let mut fbb = flatbuffers::FlatBufferBuilder::new();
+            let points = models_helper::create_big_random_points(&mut fbb, 10);
+            fbb.finish(points, None);
+            let points = fbb.finished_data().to_vec();
 
-        let request = kv_service::WritePointsRpcRequest { version: 1, database, points };
+            let request = kv_service::WritePointsRpcRequest { version: 1, database, points };
```
Comment (zipper-meng) [inline tskv/src/kvcore.rs:600]: Haven't run `make fmt`?

**Review by roseboy-liu — APPROVED** [review]
LGTM
