### PR TITLE
fix: fix CREATE TABLE parse error

### LINKED ISSUE #1126: A question about the create statement
cnosdb version：[ef1b5d0dcc9d3db0858e8d850a89b07b3c839a5f](https://github.com/cnosdb/cnosdb/commit/ef1b5d0dcc9d3db0858e8d850a89b07b3c839a5f)
I find that this statement can be executed
> create table test(col bigint,);

But this statement is executing with an error
create语句问题

### PR DESCRIPTION
**Pull request by ZuoTiJia**
# Which issue does this PR close?

Close #1126

### CODE REVIEW

File: query_server/query/src/sql/parser.rs [hunk 1]
```diff
@@ -1610,6 +1595,29 @@ mod tests {
...
+                    is_tag: false,
+                    data_type: DataType::BigInt(None),
+                    encoding: None
+                }]
+            })
+        );
+
+        let sql = "CREATE TABLE test(column1 BIGINT,);";
+        let statement2 = ExtParser::parse_sql(sql).unwrap().pop_front().unwrap();
+        assert_eq!(statement1, statement2);
```
Comment (yukkit) [inline query_server/query/src/sql/parser.rs:1618]: Should this syntax be an error?

Comment (ZuoTiJia) [reply query_server/query/src/sql/parser.rs:1618]: I agree with you.

**Review by yukkit — APPROVED** [review]
